apiVersion: batch/v1
kind: CronJob
metadata:
  name: myapp-cronjob
spec:
  schedule: "0 * * * *"  # Replace with your desired cron schedule (runs every hour in this example)
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
          - name: myapp
            image: acrstage.azurecr.io/semi22/my-talend-job:latest
            ports:
            - containerPort: 80
          restartPolicy: Never  # Or use Never if you want the job to run exactly once per scheduled time
